### PR TITLE
Fixed UserMixin/flask-login problem

### PR DESCRIPTION
**Pull request by missingcharacter**
Flask-Login 0.3.0 changed is_authenticated() from a method to a property, I changed "current_user.is_authenticated()" to "current_user.is_authenticated" to make the examples work with newer versions.

BTW, this is a great course, thank you for your efforts.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Could you update the requirements file as well? Thanks!

**Comment by missingcharacter** [comment]
Sorry about that, I forgot about the requirements file. It should be good now.

**Comment by missingcharacter** [comment]
dominate is a dependancy of Flask-Bootstrap 3.3.5.6

```
$ yolk -d flask-bootstrap
Flask-Bootstrap 3.3.5.6
  dominate
  Flask>=0.8
```

**Comment by miguelgrinberg** [comment]
So my problem now is that I need to verify all the examples to make sure they work with the new requirements. Would you be okay leaving all requirements except Flask-Login at the versions they were originally? That makes this change a lot smaller in scope. We can look at updating all the other requirements separately.

**Comment by missingcharacter** [comment]
Sure, let me try that and then update again.

**Comment by missingcharacter** [comment]
Sorry for the long delay, finally I made the changes you requested, let me know if I missed something.

**Comment by miguelgrinberg** [comment]
Thank you, this is now merged.

**Pull request closed without merging**
